const Path = require("path");
const { playSound } = require("../helpers");

module.exports = {
	name: "dear-diary",
	description: "Give me a quote from our Malle 21 trip",
	aliases: ["malle21", "tagebuch", "diary", "liebes-tagebuch", "leibes-tagebuch"],
	execute: async message => {
		const malleQuotes = [
			"wir müssen zwei Stunden auf unser Mietauto warten. Markus sagt 'alles ist scheisse'",
			"Felix will sich zum neuen Führer aufschwingen",
			"Felix hat nur eine halbe Freunding, er will nichts anbrennen lassen!",
			"Felix versucht Pascal anzugrapschen",
			"I LOVE FASTER",
			"Müller hat nichts mehr zu sagen bei Key-Systems.",
			"Mark will vom IBS-Brand weg, laut Felix, weil der Brand kacke ist",
			"PASCAL braucht Kippen und ist auch eine Programmiersprache",
			"Wir stehen immer noch beim Autoverleih aber gerade ist Slottery",
			"Müller verhandelt mit dem Autohändler. Er will keine extra Versicherungen abschließen, aber der Händler ist scharf auf sein Fell. Eine lange und harte Verhandlungsrunde steht uns bevor.",
			"Der kanadische Koreaner wollte von Felix wissen wie viele Feiertage es in Deutschland gibt.",
			"Müller ist ein sehr aggressiver Autofahrer #schrecken-der-strasse #schrecken-von-palma",
			"das Niveau sank sehr schnell",
			"Dommes Kimme klebt",
			"Domme denkt er wäre viel männlicher als ich",
			"Wir machen es jetzt hier als Zwischenlager in den Sand, ... und nachher ins Endlager. Domme 19:00 Uhr",
			"Domme will Desi heiraten, aber bitte lieber Gott, ERZÄHL ES NICHT!",
			"Der alte Knauser (Domme) hat nur 500,- € reingesteckt, da hätte er lieber ne Grafikkarte gekauft. Naja, er hat sonst ja auch noch nix reingesteckt.",
			"FAIR IS FAIR",
			"Felix sagt: Man bekommt das Kopfweh nicht, weil man Wein auf Bier trinkt, sondern weil man zuviel trinkt",
			"Felix Doktrin: Es kommt nicht auf die Reihenfolge des Alkohols an, sondern rein auf die Menge",
			"Bassi: Och, hinter der Bucht ist ja Meer #captain-obvious",
			"Die DKB sind Hurensöhne, die verlangen Gebühr",
			"Michel: Wir haben ne Nutte die uns unter der Dusche einen bläst. Und danach die Toilette reinigt. Domme: Deshalb brauchen wir keine Klobürste, die Nutte leckt das sauber. Deshalb lohnen sich auch die kleinen Thai-Hände.",
			"GIVE ME SOME SCHNAAAAAAAEPS",
			"5 Shishas pro Tag reichen sicher aus. 10 Stunden und 10 Shishas später: 'War vielleicht etwas naiv'",
			"Flo bespasst uns die ganze Zeit aus der Toilette raus",
			"Och Jungs, würgt ihr eure Freundin eigentlich auch?",
			"Wie lange war deine letzte monogame Beziehung? #deeptalk",
			"Warum stehst du jeden morgen auf? #Captain Deeptalk",
			"Ich glaube, du siehst aus wie ein Schlagersänger. Ne, ich mach M&A. Aber du machst doch sicher nicht die Kleinen platt. Sicher??? Schlampe 1 zu Hanno Herzlich.",
			"Du siehst aus wie ein Erzieher! Ich liebe Kinder.",
			"Ich bin nur körperlich jüdisch. Meine Eichel ist ganz wund!",
			"Flo lügt Felix an dass der Bacardi leer ist #betrayal-of-the-year",
			"Ich hab nicht 'Triple Anal' gesagt. Es war nur 'Double Anal' #much-better",
			"Ach, du bist der Nüchterne hier. Ne, ich beobachte nur gern. #mr-creepy",
			"Corona ist jetzt Coroni",
			"Was treibt dich an? #captain-deeptalk",
			"Domme gesteht Pascal seine Liebe. Zwei Stunden später macht er mit Bassi rum. #super-emotional-and-slutty",
			"Warum willst du nicht mit mir Kreuzpissen. #rejection",
			"Ich muss so langsam mal ab an den Beach. Zu viele Schwänze gesehen.",
			"Sprühschissregen - Da zieht Flo mal ein frischgebügeltes weißes Hemd an...",
			"Frauen können einfach nicht zocken. Die sind einfach dumm!",
			"So Flo, noch ein Bier dann fahren wir - Beide Fahrer stossen an -",
			"Domme was machst du da? Ich doch ne wunde Eichel!",
			"Bier ist das neue Wasser!",
			"respect the unrespected",
			"Schlampe1: Ich fühle mich wie ein Kerl",
			"LEASH THE UNLEASHED",
			"RASIER DIE UNRASIERT",
			"SCHNÄPS THE UNSCHNÄPSED",
			"BURN THE UNBURNT",
			"smoke the unsmoked",
			"Jungs, wir haben nur noch 8 Paletten Bier, das reicht niemals! Kauft mal noch 10",
			"Morgens um 10. Oh, da sind ja noch Bitches im Pool.",
			"Michi ist im Krebs Modus",
			"Domme: Wo ist mein Ladekabel? Chris: Das liegt unterm Bett. Domme: Ne, das ist da ned. Chris schaut nach und natürlich liegt es direkt unterm Bett.",
			"Ein Esssen ist nicht genug!",
			"Eh eh eh eh eh Ah ah ah ah ah eh eh eh eh eh ah ah ah ah ah",
			"Viva la noche",
			"#doppelleben - you only live twice",
			"#die-saufnomaden",
			"Ich steh nicht so auf Dreier, wenn ich zwei Leute gleichzeitig enttäuschen will, dann besuche ich meine Eltern.",
			"Vegetarisches Essen das nach Fleisch schmeckt ist das gleiche wie ein Dildo. Befriedigt dich vielleicht, ist aber einfach nicht echt. #schwanz",
		];

		const randomQuote = malleQuotes[Math.floor(Math.random() * malleQuotes.length)];

		return message.channel.send(`Liebes Tagebuch, ${randomQuote}`, { tts: true });
	},
};
